# From: https://about.gitlab.com/2017/09/21/how-to-create-ci-cd-pipeline-with-autodeploy-to-kubernetes-using-gitlab-and-helm/

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - vendor/

variables:
  REPO_DIR: gitlab.com/privategrity
  REPO_NAME: client
  DOCKER_IMAGE: carback1/golang-glide:1.9-4a49ace8cac8
  MIN_CODE_COVERAGE: "70.0"

before_script:
  ##
  ## Go Setup
  ##
  - go version || echo "Go executable not found."
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - mkdir -p $GOPATH/src/$REPO_DIR
  - ln -s $CI_PROJECT_DIR $GOPATH/src/$REPO_DIR/$REPO_NAME
  - cd $GOPATH/src/$REPO_DIR/$REPO_NAME
  - echo $PWD

stages:
  - setup
  - test
  - build
  - release
  - deploy
  - trigger_integration

setup:
  stage: setup
  image: $DOCKER_IMAGE
  script:
    # https://docs.gitlab.com/ee/ci/ssh_keys/README.html

    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)

    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ##
    ## Add SSH key for gitlab.com
    ##
    - ssh-keyscan -t rsa gitlab.com > ~/.ssh/known_hosts

    ##
    ## Glide diagnostics
    ##
    - glide --version

    - git clean -ffdx
    - rm -fr /root/.glide
    - rm -fr ~/.glide
    - glide install -v
  artifacts:
    paths:
     - vendor/

test:
  stage: test
  image: $DOCKER_IMAGE
  script:
    - mkdir -p testdata

    # Test coverage
    - goverage -coverprofile=testdata/coverage.out -v ./... 2>&1 | grep -v "no packages being tested depend on"
    # Exclude some specific packages and files
    - cat testdata/coverage.out | grep -v cmd | grep -v mockserver > testdata/coverage-real.out
    - go tool cover -func=testdata/coverage-real.out
    - go tool cover -html=testdata/coverage-real.out -o testdata/coverage.html

    # Test Coverage Check
    - go tool cover -func=testdata/coverage-real.out | grep "total:" | awk '{print $3}' | sed 's/\%//g' > testdata/coverage-percentage.txt
    - export CODE_CHECK=$(echo "$(cat testdata/coverage-percentage.txt) >= $MIN_CODE_COVERAGE" | bc -l)
    - (if [ "$CODE_CHECK" == "1" ]; then echo "Minimum coverage of $MIN_CODE_COVERAGE succeeded"; else echo "Minimum coverage of $MIN_CODE_COVERAGE failed"; exit 1; fi);
  artifacts:
    paths:
      - testdata/

build:
  stage: build
  image: $DOCKER_IMAGE
  script:
    - mkdir -p release
    - go generate cmd/version.go
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-w -s' ./...
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-w -s' -o release/client.linux64 main.go
    - GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-w -s' -o release/client.win64 main.go
    - GOOS=windows GOARCH=386 CGO_ENABLED=0 go build -ldflags '-w -s' -o release/client.win32 main.go
    - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-w -s' -o release/client.darwin64 main.go
    - release/client.linux64 --version
  artifacts:
    paths:
     - release/

release:
  stage: release
  image: docker:latest
  script:
    - cd release
    # - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    # - docker build -t ${CONTAINER_IMAGE} .
    # - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    # - docker push ${CONTAINER_IMAGE}
    # - docker push ${CONTAINER_IMAGE_LATEST}

deploy_staging:
  stage: deploy
  image: lwolf/helm-kubectl-docker:v152_213
  before_script:
    - mkdir -p /etc/deploy
    # - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    # - kubectl config use-context homekube
    # - helm init --client-only
    # - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
    # - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
    # - helm repo update
  script:
    - cd /etc/deploy
    # - helm dep build
    # - export API_VERSION="$(grep "appVersion" Chart.yaml | cut -d" " -f2)"
    # - export RELEASE_NAME="libr-files-v${API_VERSION/./-}"
    # - export DEPLOYS=$(helm ls | grep $RELEASE_NAME | wc -l)
    # - if [ ${DEPLOYS}  -eq 0 ]; then helm install --name=${RELEASE_NAME} . --namespace=${STAGING_NAMESPACE}; else helm upgrade ${RELEASE_NAME} . --namespace=${STAGING_NAMESPACE}; fi
  environment:
    name: staging
    # url: https://librerio.example.com
  only:
  - master

trigger_integration:
  stage: trigger_integration
  script:
    - "curl -X POST -F token=e34aa19ef1530e579c5d590873d3c6 -F ref=master https://gitlab.com/api/v4/projects/5615854/trigger/pipeline"
    - "curl -X POST -F token=d1888aeb7d0e1e6573b313a59ff16e -F ref=master https://gitlab.com/api/v4/projects/5681102/trigger/pipeline"
    # channelbot
    - "curl -X POST -F token=de4b7c93b0c2ce5d76e8780ab0fd73 -F ref=master https://gitlab.com/api/v4/projects/6204331/trigger/pipeline"
  only:
    - master
