# From: https://about.gitlab.com/2017/09/21/how-to-create-ci-cd-pipeline-with-autodeploy-to-kubernetes-using-gitlab-and-helm/

variables:
  REPO_DIR: gitlab.com/elixxir
  REPO_NAME: client
  DOCKER_IMAGE: elixxirlabs/cuda-go:go1.16-cuda11.1
  MIN_CODE_COVERAGE: "35"

before_script:
  ##
  ## Go Setup
  ##
  - go version || echo "Go executable not found."
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - echo $PWD
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -t rsa gitlab.com > ~/.ssh/known_hosts
  - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - export PATH=$HOME/go/bin:$PATH
  - export GOPRIVATE="*gitlab.com/elixxir/*,*gitlab.com/xx_network/*"


stages:
  - test
  - build
  - trigger_integration
  - trigger_release_integration

test:
  stage: test
  image: $DOCKER_IMAGE
  except:
    - tags
  script:
    - git clean -ffdx
    - go mod vendor -v
    - go build ./...
    - go mod tidy
    - mkdir -p testdata

    # Test coverage
    - go-acc --covermode atomic --output testdata/coverage.out ./... -- -v
    # Exclude some specific packages and files
    - cat testdata/coverage.out | grep -v cmd | grep -v mockserver | grep -v pb[.]go | grep -v main.go > testdata/coverage-real.out
    - go tool cover -func=testdata/coverage-real.out
    - go tool cover -html=testdata/coverage-real.out -o testdata/coverage.html

    # Test Coverage Check
    - go tool cover -func=testdata/coverage-real.out | grep "total:" | awk '{print $3}' | sed 's/\%//g' > testdata/coverage-percentage.txt
    - export CODE_CHECK=$(echo "$(cat testdata/coverage-percentage.txt) >= $MIN_CODE_COVERAGE" | bc -l)
    - (if [ "$CODE_CHECK" == "1" ]; then echo "Minimum coverage of $MIN_CODE_COVERAGE succeeded"; else echo "Minimum coverage of $MIN_CODE_COVERAGE failed"; exit 1; fi);
  artifacts:
    paths:
      - vendor/
      - testdata/

build:
  stage: build
  image: $DOCKER_IMAGE
  except:
    - tags
  script:
    - mkdir -p release
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-w -s' ./...
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-w -s' -o release/client.linux64 main.go
    - GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-w -s' -o release/client.win64 main.go
#    - GOOS=windows GOARCH=386 CGO_ENABLED=0 go build -ldflags '-w -s' -o release/client.win32 main.go
    - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-w -s' -o release/client.darwin64 main.go
    - /upload-artifacts.sh release/
  artifacts:
    paths:
     - release/

tag:
    stage: trigger_integration
    only:
        - master
    image: $DOCKER_IMAGE
    script:
        - git remote add origin_tags git@gitlab.com:elixxir/client.git || true
        - git tag $(release/client.linux64 version | grep "Elixxir Client v"| cut -d ' ' -f3) -f
        - git push origin_tags -f --tags

bindings:
  stage: build
  except:
    - tags
  tags:
    - ios
  script:
    - export PATH="/usr/local/opt/go@1.13/bin:$PATH"
    - go get -u golang.org/x/mobile/cmd/gomobile
    - go get -u golang.org/x/mobile/bind
    - rm -rf $HOME/go/src/gitlab.com/elixxir/client/
    - mkdir -p $HOME/go/src/gitlab.com/elixxir/client/
    - cp -r * $HOME/go/src/gitlab.com/elixxir/client/
    - GO111MODULE=on gomobile bind -target android -androidapi 21 gitlab.com/elixxir/client/bindings
    - GO111MODULE=on gomobile bind -target ios gitlab.com/elixxir/client/bindings
    - zip -r iOS.zip Bindings.framework
  artifacts:
    paths:
      - iOS.zip
      - bindings.aar
      - bindings-sources.jar

trigger_integration:
  stage: trigger_integration
  script:
    # UDB
    - "curl -X POST -F token=dcf1a672991bbc2520e96cea271b5a -F ref=master https://gitlab.com/api/v4/projects/6317316/trigger/pipeline"
    # integration
    - "curl -X POST -F token=e34aa19ef1530e579c5d590873d3c6 -F ref=master https://gitlab.com/api/v4/projects/5615854/trigger/pipeline"
  only:
    - master

trigger_release_integration:
  stage: trigger_release_integration
  script:
    # UDB
    - "curl -X POST -F token=dcf1a672991bbc2520e96cea271b5a -F ref=release https://gitlab.com/api/v4/projects/6317316/trigger/pipeline"
    # integration
    - "curl -X POST -F token=e34aa19ef1530e579c5d590873d3c6 -F ref=release -F \"variables[CLIENT_ID]=release\" -F \"variables[GATEWAY_ID]=release\" -F \"variables[REGISTRATION_ID]=release\" -F \"variables[SERVER_ID]=release\" -F \"variables[UDB_ID]=release\" https://gitlab.com/api/v4/projects/5615854/trigger/pipeline"
  only:
    - release
